//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankService.paymentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="inTimeReqPara", Namespace="http://schemas.datacontract.org/2004/07/paymentSOA")]
    [System.SerializableAttribute()]
    public partial class inTimeReqPara : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReqIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReqId {
            get {
                return this.ReqIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReqIdField, value) != true)) {
                    this.ReqIdField = value;
                    this.RaisePropertyChanged("ReqId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="paymentEntity", Namespace="http://schemas.datacontract.org/2004/07/paymentSOA")]
    [System.SerializableAttribute()]
    public partial class paymentEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillNo {
            get {
                return this.BillNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BillNoField, value) != true)) {
                    this.BillNoField = value;
                    this.RaisePropertyChanged("BillNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="inTimeEntity", Namespace="http://schemas.datacontract.org/2004/07/paymentSOA")]
    [System.SerializableAttribute()]
    public partial class inTimeEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bankService.paymentService.bankEntity BankEntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bankService.paymentService.bankEntity BankEnt {
            get {
                return this.BankEntField;
            }
            set {
                if ((object.ReferenceEquals(this.BankEntField, value) != true)) {
                    this.BankEntField = value;
                    this.RaisePropertyChanged("BankEnt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentResult {
            get {
                return this.PaymentResultField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentResultField, value) != true)) {
                    this.PaymentResultField = value;
                    this.RaisePropertyChanged("PaymentResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="bankEntity", Namespace="http://schemas.datacontract.org/2004/07/bankService")]
    [System.SerializableAttribute()]
    public partial class bankEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayId {
            get {
                return this.PayIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PayIdField, value) != true)) {
                    this.PayIdField = value;
                    this.RaisePropertyChanged("PayId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="paymentService.IPaymentService")]
    public interface IPaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/createBill", ReplyAction="http://tempuri.org/IPaymentService/createBillResponse")]
        bankService.paymentService.paymentEntity createBill(bankService.paymentService.inTimeReqPara para);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/paymentResultHook", ReplyAction="http://tempuri.org/IPaymentService/paymentResultHookResponse")]
        void paymentResultHook(bankService.paymentService.inTimeEntity payResult);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/createBillHelp", ReplyAction="http://tempuri.org/IPaymentService/createBillHelpResponse")]
        bankService.paymentService.paymentEntity createBillHelp(bankService.paymentService.inTimeReqPara para);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/paymentResultHookHelp", ReplyAction="http://tempuri.org/IPaymentService/paymentResultHookHelpResponse")]
        void paymentResultHookHelp(bankService.paymentService.inTimeEntity payResult);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentServiceChannel : bankService.paymentService.IPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<bankService.paymentService.IPaymentService>, bankService.paymentService.IPaymentService {
        
        public PaymentServiceClient() {
        }
        
        public PaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bankService.paymentService.paymentEntity createBill(bankService.paymentService.inTimeReqPara para) {
            return base.Channel.createBill(para);
        }
        
        public void paymentResultHook(bankService.paymentService.inTimeEntity payResult) {
            base.Channel.paymentResultHook(payResult);
        }
        
        public bankService.paymentService.paymentEntity createBillHelp(bankService.paymentService.inTimeReqPara para) {
            return base.Channel.createBillHelp(para);
        }
        
        public void paymentResultHookHelp(bankService.paymentService.inTimeEntity payResult) {
            base.Channel.paymentResultHookHelp(payResult);
        }
    }
}
